# This workflow will run tests on this project using maven

name: Tests

on:
  push:
    branches: [ master, feature/*, bugfix/* ]
  pull_request:
    branches: [ master, feature/*, bugfix/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Run tests
      run: mvn -Dexec.skip test
